### ISSUE TITLE
As a reader, I want to navigate around the site using a custom navigation in the header.

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/startwords#60]
# testing notes

- the hiding/"pitbar" behavior for this isn't implemented yet; that will be tracked on #66.
- it should look the same on all pages.
- it should always be visible.

# dev notes
this is the menu that appears vertically along the top left portion of the page on all pages. it always contains links to the homepage and the issues list page.

**Comment by gwijthoff** [comment]
Is the home & issue button/links showing up like this in anyone else's browser? It's the case for me on my iPhone and my tablet in both Firefox and Safari. Looks as designed on my laptop though. 

![IMG_5469.jpg](https://images.zenhubusercontent.com/5e6fa2284847cbacb75fdd35/d403f92f-05b6-4a8b-970a-e2eafcaefbe0)

**Comment by thatbudakguy** [comment]
@gwijthoff I tested on an iPad just now and it looked OK in both safari and firefox. this might be a cache problem - this issue was happening earlier and I deployed a fix, so maybe you have an old version cached. try clearing your data?

**Comment by gissoo** [comment]
@thatbudakguy This is still happening to me only on Safari now that I check for the first time.

**Comment by rlskoeser** [comment]
@thatbudakguy I was able to replicate with Safari on an iPad. IDK why it's needed, maybe older devices have older versions of the browsers? 

@gwijthoff @gissoo I added a webkit specific variant of the clip-path that's used for the nav shapes. It's on the site, so you can review and confirm it's working on your devices now.

**Comment by gwijthoff** [comment]
@rlskoeser that fixed it for me! Home & issue button/links now look as they should on my phone and tablet.

**Comment by thatbudakguy** [comment]
@rlskoeser thanks for doing that!

out of curiousity, could @gissoo or @gwijthoff check your version of iOS safari? compat tables say that the vendor prefix hasn't been needed since version 9, and the current version is 13, so would be good to know if some devices are indeed that far behind.

**Comment by gwijthoff** [comment]
@thatbudakguy I was using Firefox 24.1 (17574) on an iPhone 6s running iOS 13.3.1

**Comment by thatbudakguy** [comment]
huh... the compatibility tables don't even list anything for Firefox on iOS. the Firefox on Android current version is 68, so I guess Firefox on iOS is on a totally different versioning schedule. thanks for checking!

**Comment by gissoo** [comment]
@thatbudakguy Sorry for the delay, was planning to test this earlier this week – It was only happening to me on Safari on desktop, I just tested now on my mobile (safari) and on my desktop Safari, Firefox, and Chrome) and it looks fine – )Side note: I'm having a lot of storage issues on my phone right now, so haven't been able to test on Firefox and Chrome on my phone – will test issues when I solve the problems with my phone!)
